---
- name: playbook de teste
  hosts: all
  become: yes

  tasks:
  - name:
    debug:
      msg: "The inventory_hostname is {{ inventory_hostname }}"
  
  roles:
    - role: /home/chaveslab/labchaves/aprendizado_ansible/roles/git
      
